project:
  type: website

website:
  title: "Us Vehicle Sales"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: plot-2.qmd
      - href: plot-3.qmd
      - href: plot-4.qmd
      - href: about.qmd
      - href: sources.qmd
        text: Sources
      

format:
  html:
    theme: darkly
    css: styles.css
    toc: true



