project:
  type: website

website:
  title: "Us Vehicle Sales"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
      - href: sources.qmd
        text: Sources

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



